# Generated by Django 3.0.8 on 2020-08-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
